import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Luis Terra :: Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{ backgroundImage: 'url("/background.jpeg")' }}
        className="h-full w-full fixed text-white bg-fixed bg-cover [background-position-x:200px] [background-position-y:35%]"
      >
        {/* Background image and gradient */}
        <div
          className="w-2/3 h-full fixed bg-gradient-to-r from-black/90 to-transparent backdrop-filter backdrop-blur-lg"
          style={{
            WebkitMaskImage:
              "linear-gradient(to right, black, black 40%, transparent)",
          }}
        >
          {" "}
        </div>

        {/* Content */}
        <div className="fixed top-0 left-0 flex flex-col justify-center items-left h-full w-1/2 ml-[10%] space-y-20">
          <div className="block text-center w-fit">
            <h1 className="text:6xl md:text-9xl font-thin">
              Luis<span className="font-semibold">Terra</span>
            </h1>
            <p className="text-3xl font-light">cantor • compositor</p>
          </div>

          {/* Menu */}
          <div className="flex flex-col h-[20rem] text-2xl">
            <div className="flex-1">
              <a href="/about">sobre</a>
            </div>
            <div className="flex-1">
              <a href="/music">portfólio</a>
            </div>
            <div className="flex-1">
              <a href="/music">poesias</a>
            </div>
            <div className="flex-1">
              <a href="/music">letras</a>
            </div>
            <div className="flex-1">
              <a href="/contact">contato</a>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
